openai/openai-openapi

- openapi.yaml
The `id` and `model` properties are defined in the `CreateEditResponse` schema, but these properties are not returned by the `POST` `/edits` endpoint.
These two properties are also listed as required, which causes issues with [tools/libraries using this OpenAPI specification](https://github.com/tectalichq/public-openai-client-php/discussions/11).
Your [Postman Collection](https://www.postman.com/devrel/workspace/openai/documentation/13183464-90abb798-cb85-43cb-ba3a-ae7941e968da?entity=&branch=&version=) does not list these properties for the Create Edit response, it only lists `object`, `created`, `choices` and `usage`.
This pull request removes these `id` and `model` properties from the OpenAPI schema.
Example JSON response: from `https://api.openai.com/v1/edits` as of today:
```json
{ …
```
> Remove incorrect `id` and `model` properties from `CreateEditResponse`

- openapi.yaml
Users almost always want to send this – they can always send null, empty string, or empty array if they really want an empty prompt.
> Mark `POST /completions` `prompt` as a required param

- openapi.yaml
I'm not sure whether this is actually the case (please decline the PR if not!) but I would expect all keys of this object to be present in all responses (though of course logprobs is marked as sometimes having a `null` value).
Making this change would enable nicer types, eg, `response.choices[0].text.length` rather than `response.choices[0].text?.length`
> Mark all properties in "choices" as required

- openapi.yaml
This just fixes the summary of the Create Translation section from "Translates audio into into English." to "Translates audio into English."
> Removes an extra word in the Create Translation section summary

- openapi.yaml
In https://github.com/openai/openai-node/issues/181#issuecomment-1611712836, a user claimed that a function without `parameters` specified will not be called, but the same function with `parameters: { 'type': 'object', properties: {} }` is called. This leads me to believe that the user should always pass `parameters`, even if they must be an empty object.
A better approach to marking this required might be to make this the default on the server side, so that users do not need to pass this object for functions which accept no parameters. However, in case that'll take some time to get to, I wanted to put up this PR for now to improve the DX in the meantime.
> Mark function.parameters as required

- openapi.yaml
`anyOf` is the right OpenAPI feature to use here as `oneOf` implies exclusivity.
> Use anyOf for enums with suggested values

- openapi.yaml
See https://github.com/openai/openai-node/issues/95; the `prompt` must be specified before the `mask`, unfortunately.
This should be obsolete soon, but may as well fix.
> Fix code sample for image edits

- openapi.yaml
I noticed this when looking into https://github.com/openai/openai-node/issues/155
I simply copied the options from the documentation; I'm not certain the list is exhaustive.
> Add `response_format` enum to transcriptions

- openapi.yaml
Attempts to resolve https://github.com/openai/openai-node/issues/82
Note I am very uncertain whether these changes are correct; they are just guesses. Please audit them before merging.
> Mark `finish_reason` and other properties as required

- openapi.yaml
Adds missing moderation categories that are mentioned in the docs: https://platform.openai.com/docs/guides/moderation/overview. I haven't independently verified that these properties are included by the API.
I've also updated the descriptions to match the docs as those descriptions are more helpful.
Reported here: https://github.com/openai/openai-node/issues/223
> Update moderation categories to match docs

- openapi.yaml
Sets the `maxItems` on functions to 128.
> Update functions limit to 128

- openapi.yaml
The API docs indicate that this exists, but I haven't verified by checking API responses.
> Add id to fine-tuning job events

- openapi.yaml
Would address https://github.com/openai/openai-node/issues/320
I have not verified whether this or https://platform.openai.com/docs/guides/gpt/chat-completions-api is more accurate on this subject.
> fix: add content_filter and function_call to finish_reason

- openapi.yaml
- pending -> queued
- introduce "validating_files" status
- mark finished_at, n_epochs, and all error properties as required
> Updates to fine-tuning spec

- openapi.yaml
The docs imply this is optional: https://platform.openai.com/docs/assistants/overview/step-2-create-a-thread
Addresses https://github.com/openai/openai-node/issues/448
> Don't mark `post /threads` request body as required

- openapi.yaml
The current object is set `embedding` but the API returns `list` instead.
Example:
```sh
curl https://api.openai.com/v1/embeddings \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-H "Content-Type: application/json" \
-d '{
"input": "The food was delicious and the waiter...",
"model": "text-embedding-ada-002",
"encoding_format": "float"
}'
```
Response:
```json
{
"object": "list",
"data": [
{
"object": "embedding",
"index": 0,
"embedding": [ 0.0022579778, ...]
}
],
"model": "text-embedding-ada-002-v2",
"usage": {
"prompt_tokens": 8,
"total_tokens": 8
}
}
```
cc @schnerd
> Fix CreateEmbeddingResponse object type

- openapi.yaml
This param is a required path param, not a body param.
> Fix accidental inclusion of thread_id in required

- openapi.yaml
> Extract ChatCompletionTokenLogprob schema

- openapi.yaml
This fixes issue reported here - https://github.com/openai/openai-node/issues/939 where the VectorStoreObject's last_error.codes were different from what the API response received.
> Fix the vector store object's last_error.codes

- openapi.yaml
This results in the generated SDKs just using `str` which I don't think is intentional - https://github.com/openai/openai-python/blob/89e5a010b22136f0f16eff5ec33105f4d3e273eb/src/openai/resources/audio/translations.py#L54
> Fix missing translations response_format enum

- openapi.yaml
Update definitions for recent releases of moderation and reasoning models!
> Update for reasoning and moderation

- openapi.yaml
Corresponds to API definition update https://github.com/openai/openai/pull/167504
> Revert app use case fields for project

- openapi.yaml
Synced from https://github.com/openai/openai/pull/195682
> [Rate Limits API] API Documentation

- openapi.yaml
Remove spec validation errors for client generation tools
> Remove spec errors
