openai/openai-openapi

- openapi.yaml
The fix resolves an issue with invalid JSON.
> The last parameter item does not require comma.

- openapi.yaml
Per @jongwook in https://github.com/openai/whisper/discussions/799#discussioncomment-6432285 (I have not independently verified that this is accurate). cc @athyuttamre
> Document that FLAC and OGG filetypes are accepted in Whisper endpoints

- openapi.yaml
> Add code samples for openai-node v4

- openapi.yaml
Missed this in https://github.com/openai/openai-openapi/pull/88
Fixes https://github.com/openai/openai-node/issues/337
cc @athyuttamre
> Add content_filter to chat completion chunks

- openapi.yaml
> Add gpt-4-1106-preview and gpt-4-vision-preview

- openapi.yaml
Addresses https://github.com/openai/openai-node/issues/443
cc @schnerd
> add system_fingerprint to chat completion chunks

- openapi.yaml
https://github.com/openai/openai-node/issues/444
cc @logankilpatrick @nknj
> Add gpt-3.5-turbo-1106

- openapi.yaml
https://github.com/openai/openai-python/issues/1107
> Remove 'type: object' from tool_calls item

- openapi.yaml
This reverts commit 1d1e8eab16ecb7a1425cb579b717d6ef765412ff.
> Revert "Add instance_id param to chat completions"

- openapi.yaml
> Add wav and pcm to supported audio response_format

- openapi.yaml
also include a previous typo fixing
> [batchapi] add list batch

- openapi.yaml
Reverts openai/openai-openapi#242
> Revert "add required as an option for tool_choice in chat/completions api"

- openapi.yaml
Reverts openai/openai-openapi#244
> Add required as an option for tool_choice in chat/completions api

- openapi.yaml
Update OpenAPI with Uploads, allowing users to upload large files in multiple parts.
> Update OpenAPI with Uploads

- openapi.yaml
> Adds path params to Uploads

- openapi.yaml
Add `gpt-4o-mini`, `gpt-4o-mini-2024-07-18` to 
- `CreateChatCompletionRequest`
- `CreateAssistantRequest`
- `CreateRunRequest`
- `CreateThreadAndRunRequest`
> Add gpt-4o-mini

- openapi.yaml
Coming from user PR https://github.com/openai/openai-python/pull/1570
> Fix typo maxium -> maximum

- openapi.yaml
https://github.com/openai/openai-python/pull/1755#discussion_r1782898141
> Fix audio duration types

- openapi.yaml
Add Usage API and sync with other updates
> Usage API and other updates

- openapi.yaml
Add const types for Stainless SDK
> Spec update 2025-01-21

- openapi.yaml
> Update the spec for o3-mini launch

- openapi.yaml
Updating for latest API version.
> Updates 2025-03-11
